### ISSUE TITLE
Markdown parser depends on Renderer, works strangely when Renderer isn't HTML-like.

### ISSUE THREAD

**Issue by dmitshur** [russross/blackfriday#106]
From README,

> Blackfriday is structured to allow alternative rendering engines.

It does so by exposing a Renderer interface, which in theory any renderer can implement.

What makes it difficult and restrictive to implement certain renderers is that the Markdown parser itself depends on the renderer doing certain things, and will fail or act in unexpected ways if that's not the case.

I think a better design would have it so that the Markdown parser is independent of the renderer. A Markdown document should be parsed the same way regardless of renderer used.

_One example_ of the parser depending on the Renderer is the `LineBreak` method of the `Renderer` interface. If `EXTENSION_HARD_LINE_BREAK` is not enabled, then `LineBreak` is only called if the renderer preserved spaces. E.g., see:

https://github.com/russross/blackfriday/blob/52f7a2a7b02d11db19411c28e6c67fc351f20aaf/inline.go#L157-L176

First, note that the parser actually trims spaces off the end of line (isn't it the renderer's job to decide how the output should look like?). What happens if the renderer does not render those spaces, then `LineBreak` method is never called.

**Comment by shurcooL** [comment]
For posterity, this issue is not completely resolved.

It was closed when #107 was merged into master because the PR description mention "Partially fixes #106.", which inadvertently triggered GitHub's "close issue" feature.

I will not reopen it because there's nothing really actionable in this issue left, but I wanted to mention this to avoid people thinking this issue was completely resolved by #107.
