### ISSUE TITLE
Should I push some feature from my fork?

### ISSUE THREAD

**Issue by miekg** [russross/blackfriday#135]
Hi, I forked blackfriday (and renamed it, because of all the changes, see https://github.com/miekg/mmark) and some commits later, I have implemented the following:
- Definition lists;
- Table and codeblock captions;
- Table footer;
- Quote attribution;
- Including other files;
- [TOML][3] titleblock;
- Inline Attribute Lists;
- Indices;
- Citations;
- Abstract;
- Asides;
- Notes;
- Main-, middle- and backmatter divisions;
- Example lists;
- HTML Comment parsing;
- BCP14 (RFC2119) keyword detection;
- Include raw XML references;
- Abbreviations;
- Super- and subscript.

I need most of this stuff for writing internet drafts and RFCs, so I suppose not all features
are of interest (main-, middle- and backmatter divisions, references, RFC2119, etc.).

But I could try send some of it as PRs, if there is interest?

**Comment by karland** [comment]
I am starting with Hugo coming from Middleman. I think Hugo has a lot of potential, but I am a little hesitant due to blackfriday. Middleman uses kramdown as a default but you can change it if you like. Now kramdown has a lot of very nice and useful options, that go beyond pure markdown and I use these features all the time. I think the inline attributes are especially useful since you can add `class`-elements and `data-attributes`. So I strongly vote for using extensions also in blackfriday. I actually came here for asking if there is a change that blackfriday offers functionality along the lines of kramdown. Cheers.
