### ISSUE TITLE
Proposal for new renderer: plain text

### ISSUE THREAD

**Issue by mholt** [russross/blackfriday#187]
It's quite possible there's a better way to do this, so let me know, but I'd like a way to strip markdown (and HTML) from Markdown files, essentially rendering plain text output.

I imagine this is as easy as implementing [Renderer](http://godoc.org/github.com/russross/blackfriday#Renderer) where the functions simply output their input (plus stripping HTML).

If this would do the trick, and you think it would be useful, I'd be happy to put in a PR adding a plain text implementation. (Even if you don't think it belongs in the package, let me know if it would at least work so I can do it for another project.)

**Comment by russross** [comment]
This should work just as a Renderer as you suggest. In general, I'd prefer
to keep other output formats as separate repositories and link to them from
the blackfriday README rather than merge them into the project. This is
because the vast majority of users are after HTML output; those who want
something different can just import a second package to get it. So I'd
suggest implementing it and send us a PR with a link to it in the README
file.

Someday I'll get around to splitting the LaTeX Renderer off into its own
package and removing it from the main blackfriday repo.

- Russ

**Comment by shurcooL** [comment]
> It's quite possible there's a better way to do this, so let me know, but I'd like a way to strip markdown (and HTML) from Markdown files, essentially rendering plain text output.
>
> I imagine this is as easy as implementing Renderer where the functions simply output their input (plus stripping HTML).

I think implementing `blackfriday.Renderer` interface is the best way to do it. It's almost as easy as you say, but the interface is not completely disconnected from the implementation. Be mindful of a few small gotchas, see e.g., https://github.com/russross/blackfriday/issues/106 (it's not completely resolved).

I'm aware of 2 renderers that are "close" to plain text (if I understand what you mean by plain text correctly) renderer implementations right now, I'll mention them below.

> If this would do the trick, and you think it would be useful, I'd be happy to put in a PR adding a plain text implementation. (Even if you don't think it belongs in the package, let me know if it would at least work so I can do it for another project.)

I would recommend doing it outside of this repo, but submit a PR to add it to the [list of known renderers](https://github.com/russross/blackfriday#other-renderers). Russ echoed this in the comment above, while I was still writing this comment.

Finally, if I understand what you mean by "plain text renderer" correctly, are you aware it is not a completely trivial task because of formatting? Consider Markdown input like "This is             a paragraph.". The rendered HTML will display it as "This is a paragraph." because multiple spaces appear as one space in normal paragraphs. Would your plain text renderer do the same HTML and Markdown related formatting (e.g., for tables)?

I want to point you towards a Markdown renderer (e.g. it parses Markdown via blackfriday and renders Markdown as output) I've created. It's very close to a plain text renderer, except it maintains Markdown tags (e.g., bold text will appear as \*\*bold text\*\* with the dual asterisks around it). It also has some non-trivial logic to format tables, headings, etc. You can try it online [here](http://dmitri.shuralyov.com/projects/live-markdownfmt/live-markdownfmt.html). See:

https://godoc.org/github.com/shurcooL/markdownfmt/markdown
https://github.com/shurcooL/markdownfmt

And another "text" renderer. It renders some sort of text, but I don't know if you consider it as plain text or not.

https://github.com/gholt/blackfridaytext

I don't completely know what you mean by "plain text renderer" yet, it'd be helpful you provide examples of input and output. But it sounds like you should consider just forking `markdownftm` renderer and modifying it to exclude Markdown tags. That might be the easiest way to get to the functionality you want.

**Comment by mholt** [comment]
Thanks for the detailed replies. I see now that my question was ambiguous. Basically I was looking to strip the markdown formatting characters like * and # and = and links and stuff, to just have plain text without any markdown characters. So by "plain text" I meant "plain text without Markdown formatting characters" - however, I took a look at the linked renderers and they indeed are similar to what I was looking for, so I just hacked together a quick renderer and it worked great. In fact, it ended up being somewhat specialized for our use case so no need to link to it.

Anyway, I think it's good to limit the scope of this package.

Thanks for this package, it does quite a good job!
