### ISSUE TITLE
Code blocks not rendered correctly

### ISSUE THREAD

**Issue by bkcsoft** [russross/blackfriday#279]
cross-issue from gogits/gogs#3171

> Using the characters []: breaks a code block and renders the entire line and sometimes the next line blank.

Test-case: https://gist.github.com/bkcsoft/dce1a2e16db28b46e1ce4c8df18caaba

**Comment by shurcooL** [comment]
I can reproduce, this is a valid issue in blackfriday, thanks for reporting.

**Comment by shurcooL** [comment]
Found where the bug is. It's inside `firstPass`. It erroneously tries to extract "extract references" inside fenced code blocks. We need to suppress that, just like we suppress tab expansion inside fenced code blocks.

This should be an easy fix.

**Comment by shurcooL** [comment]
It turned out to be more challenging because I discovered incidental issues that needed to be resolved first, and fixing this issue naively can cause a regression for performance (see 148) but there are no benchmarks to test for that.

I'll have a PR soon that fixes this, along with some other changes.

**Comment by rain-1** [comment]
Thanks for fixing this! I had the same problem.

If you don't mind me asking how do you use this "v2" branch? Do you add /v2 somewhere in the import line of the .go file?

**Comment by shurcooL** [comment]
@rain-1 No problem.

To use v2, use the import path `gopkg.in/russross/blackfriday.v2`.

See its documentation at https://godoc.org/gopkg.in/russross/blackfriday.v2. Learn more about it in #218.
