### ISSUE TITLE
Recommended method for previewing output?

### ISSUE THREAD

**Issue by dadatawajue** [russross/blackfriday#353]
I was wondering what everyone is doing if they want to provide preview on the frontend. The way I see it, there are two good options:

1. Use websockets to convert with blackfriday

2. Use some external JavaScript library to convert

Option 1 doesn't seem very cost efficient if it's updated on every input, whereas 
Option 2 will likely have differences in terms of how the markdown is converted.. 

Does anyone know a JavaScript library that produce exact same output as blackfriday? or how is everyone else doing it?

**Comment by shurcooL** [comment]
People do different things, depending on their requirements, budget, etc.

1. You can use a simple POST request to the backend, which uses blackfriday and sends rendered HTML as response. Using WebSocket is possible, but they're more heavyweight and not neccessary for the task.

2. I've used GopherJS compiler to compile blackfriday to JavaScript, and used that on frontend. This way, it's guaranteed to have the same output, because it's the same code.

> Option 1 doesn't seem very cost efficient if it's updated on every input

You might want to coalesce input and update less frequently. Example, after the content has stopped changing for 3 seconds. Or use a preview tab, similar to how github.com does it.

**Comment by dadatawajue** [comment]
Ahh that's great, thanks a lot <3
