### ISSUE TITLE
Bug handling HTML blockquote if no markdown outside of the blockquote

### ISSUE THREAD

**Issue by buro9** [russross/blackfriday#96]
Given this input:
```md
<blockquote>Got this today... Leg hurts

![](http://farm6.static.flickr.com/5083/5258310683_f7c87edbc4_z.jpg)</blockquote>
```

The image inside the blockquote remains as markdown after processing with blackfriday.

Out:
```html
<blockquote>Got this today... Leg hurts

![](http://farm6.static.flickr.com/5083/5258310683_f7c87edbc4_z.jpg)</blockquote>
```

Expected... the markdown image tag to become an HTML IMG element.

But, if you add *any* markdown outside of the blockquote, then the markdown image tag is converted to HTML though the HTML is invalid (nesting of paragraphs is wrong):

Input:
```md
**bold**
<blockquote>Got this today... Leg hurts

![](http://farm6.static.flickr.com/5083/5258310683_f7c87edbc4_z.jpg)</blockquote>
```

Out:
```html
<p><strong>bold</strong><br />
<blockquote>Got this today... Leg hurts</p>
		
<p><img src="http://farm6.static.flickr.com/5083/5258310683_f7c87edbc4_z.jpg" alt="" />
</blockquote></p>
```

Expected:
```html
<p><strong>bold</strong></p>
<blockquote>Got this today... Leg hurts
		
<img src="http://farm6.static.flickr.com/5083/5258310683_f7c87edbc4_z.jpg" alt="" />
</blockquote>
```

**Comment by rtfb** [comment]
It seems that this behavior is [by design](https://daringfireball.net/projects/markdown/syntax#html):

> Note that Markdown formatting syntax is not processed within block-level HTML tags. E.g., you can’t use Markdown-style *emphasis* inside an HTML block.

But here's a nice one, by doctoring your repro case a little bit I got almost exactly what you expected:

```go
func TestBQ4(t *testing.T) {
	var tests = []string{
		`**bold**
<blockquote>Got this today... Leg hurts
![](http://flickr.com/5083/img.jpg)</blockquote>
`,
		`<p><strong>bold</strong>
<blockquote>Got this today... Leg hurts
<img src="http://flickr.com/5083/img.jpg" alt="" /></blockquote></p>
`,
	}
	doTestsBlock(t, tests, 0)
}
```

I haven't debugged it in detail, but I think what happens here is this. When all the blank lines are removed, the whole thing is treated as a single paragraph, `<blockquote>` tags are treated as plain text and the image reference gets processed as if the usual markdown.

In this light, your second test case doesn't really have `<p>`s unbalanced: the input is treated as two paragraps and both get wrapped in `<p></p>`, while `<blockquote>` tags are treated as plain text.
